# Generated by Django 5.1.1 on 2024-10-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentId", models.IntegerField()),
                ("studentName", models.CharField(max_length=25)),
                ("gender", models.CharField(max_length=20)),
                ("studentAge", models.IntegerField()),
                ("studentAddress", models.CharField(max_length=80)),
            ],
        ),
    ]
